config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  post "/", to: "toppages#index"

  get "search", to: "toppages#search"
  get "comparison", to: "toppages#comparison"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comparison_item.rb
class ComparisonItem < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :check_search_validate, only: [:search]
  before_action :update_trend_words, only: [:index, :search, :comparison]
  before_action :get_category_data, only: [:index, :search, :comparison]

  def index
    @trend_word = params[:commit]
  end
  
  def search

    # 検索
    @keyword      = params.require(:search_word).permit(:content)[:content]
    @category     = params.require(:category).permit(:content)[:content]
    record        = Category.find_by(code: @category)
    @category_name= record.name

    # 検索結果取得
    puts "keyword ======> #{@keyword}"
    puts "category ======> #{@category}（#{@category_name}）"
    @is_rakuten_books = Utils::RakutenApiUtil.is_rakuten_books_search(@category)
    @rakuten_item = Utils::RakutenApiUtil.search_rakuten(@keyword, @category, 10)
    @amazon_item = Utils::AmazonApiUtil.scraping_search_amazon_site(@keyword, @category, 10)

    # モデル更新
    update_item_database(Item, @rakuten_item)
    update_item_database(ComparisonItem, @amazon_item)
  end
  
  def comparison
    
    # 楽天商品から「比較」された
    # jan code で比較する
    if params["rakuten"] != nil
      item_name = params["rakuten"][:name]
      category  = params["rakuten"][:category]
      @rakuten_item = [Item.find_by(name: item_name)]
      @amazon_item = Utils::AmazonApiUtil.scraping_search_amazon_site(@rakuten_item[0].jan_code, category, 1)
      @is_rakuten_books = Utils::RakutenApiUtil.is_rakuten_books_search(category)

    # amazonから「比較」された
    # jan code で比較する
    elsif params["amazon"] != nil
      item_name = params["amazon"][:name]
      category  = params["amazon"][:category]
      @amazon_item = [ComparisonItem.find_by(name: item_name)]
      @rakuten_item = Utils::RakutenApiUtil.search_rakuten(@amazon_item[0].jan_code, 1)
      @is_rakuten_books = Utils::RakutenApiUtil.is_rakuten_books_search(category)
    end
  end
  
  private
  def update_item_database(database_name, update_items)
  
    # 何かしら入っていたら全削除
    items = database_name.all
    if !items.empty?
      database_name.delete_all
    end
    
    update_items.each do |item|
  
      # 存在しなければレコード保存
      if database_name.find_by(name: item[:name]) == nil
        item_record = database_name.new(
          name: "#{item[:name]}", price: "#{item[:price]}",
          image_url: "#{item[:image_url]}", shop_url: "#{item[:shop_url]}",
          sales_date: "#{item[:sales_date]}",
          isbn_code: "#{item[:isbn_code]}",
          jan_code: "#{item[:jan_code]}"
        )
        item_record.save
      end
    end
  end

  def check_search_validate()

    search_word = params.require(:search_word).permit(:content)[:content]
    if search_word == ""
      flash[:danger] = "検索ワードを入力してください"
      redirect_to root_url
    end
  end
  
  def update_trend_words

    # 中身をシャッフルして格納
    trend_words = Utils::TrendwordUtil.search_trand_word()
    trend_words = trend_words.shuffle

    puts  "---------------------------"
    p  trend_words
    puts  "---------------------------"

    @trend_word_first  = trend_words[0, 3]
    @trend_word_second = trend_words[3, 3]

    @trend_word_count = 0
    if @trend_word_second != nil
      @trend_word_count = @trend_word_first.size + @trend_word_second.size
    else
      @trend_word_count = @trend_word_first.size
    end
  end
  
  def get_category_data
    @category_data = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper

end

app/views/layouts/_category_list.html.erb
<% category_data.all.each do |record| %>
  <% if record.code == check_code %>
    <option value="<%= record.code %>" selected="selected"><%= record.name %></option>
  <% else %>
    <option value="<%= record.code %>"><%= record.name %></option>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    Copyright © Hikacoo. Rights Reserved.
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="d-flex align-items-center justify-content-between">
  <%= link_to image_tag('logo.png'), '/' %>
  Amazon・楽天等 通販商品の価格を比較するサイトです。
</div>

app/views/layouts/_navbar.html.erb
<div class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Hikacoo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <li class="nav-item"><a href="/" class="nav-link">Amazon・楽天等 通販商品の
価格を比較するサイトです。</a></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_search_description.html.erb
<div class="mt-5 mb-5 text-center">
  <h2>商品価格を比較しましょう！</h2>
</div>

app/views/layouts/_searchbar.html.erb
<%= form_with(url: search_path, method: :get, local: true) do |f| %>
  <div class="form-group input-group row">
    <div class="input-group-prepend">
      <select class="form-control" id="category" name="category[content]">
        <% if @category == nil %>
          <%= render 'layouts/category_list', {category_data: @category_data, check_code: "all" } %>
        <% else %>
          <%= render 'layouts/category_list', {category_data: @category_data, check_code: @category } %>
        <% end %>
      </select>
    </div>
    <% if @trend_word == nil %>
	    <input type="text" name="search_word[content]" class="form-control" placeholder="検索キーワード入力して下さい">
    <% else %>
	    <input type="text" name="search_word[content]" class="form-control" value="<%= @trend_word %>" placeholder="検索キーワード入力して下さい" >
    <% end %>
    <div class="input-group-append">
  		<button type="submit" class="btn btn-primary search_button"><i class="fas fa-search"></i></button>
    </div>
  </div>
<% end %>

app/views/layouts/_serachbar.html.erb
<div class="mt-5 mb-5 text-center">
  <h2>商品価格を比較しましょう！</h2>
</div>
<div class="input-group">
</div>
<%= form_with(url: search_path, local: true) do |f| %>
  <div class="form-group input-group row">
    <% if @trend_word == nil %>
	    <input type="text" name="search_word[content]" class="form-control" placeholder="検索キーワード入力して下さい">
    <% else %>
	    <input type="text" name="search_word[content]" class="form-control" value="<%= @trend_word %>" placeholder="検索キーワード入力して下さい" >
    <% end %>
    <div class="input-group-append">
  		<button type="submit" class="btn btn-primary search_button"><i class="fas fa-search"></i></button>
    </div>
  </div>
<% end %>

app/views/layouts/_trend_word_list.html.erb
<div class="mt-1 pb-1 border-bottom border-dark font-default">
  <a href="https://trends.google.co.jp/trends/trendingsearches/daily?geo=JP" target="_blank">本日のトレンドワード</a>
  （ランダムで<%= @trend_word_count %>個表示してます）
</div>
<%= render 'layouts/trend_words', trend_words: @trend_word_first %>
<%= render 'layouts/trend_words', trend_words: @trend_word_second %>

app/views/layouts/_trend_words.html.erb
<div class="d-sm-flex flex-row">
  <% if trend_words == nil %>
    <% return %>
  <% end %>
  <% trend_words.each do |trend_word| %>
    <div class="mt-2 mb-2">
      <%= form_with(url: root_url, local: true) do |f| %>
        <%= f.submit trend_word, class: "mr-4 btn btn-success" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>【Hikacoo】Amazon・楽天 価格比較/検索サイト</title>
    <meta name="description" content="Amazon・楽天等 通販商品の価格を比較するサイトです。">
    <%= favicon_link_tag('favicon.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <!-- fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116278342-5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-116278342-5');
    </script>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <%= render 'layouts/header' %>
      </header>
      <div class="app ml-4 mr-4">
        <div class="container">
          <%= render 'layouts/flash_messages' %>
          <%= render 'layouts/search_description' %>
          <%= render 'layouts/searchbar' %>
          <%= render 'layouts/trend_word_list' %>
          <%= yield %>
        </div>
      </div>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>

app/views/toppages/_item_display.html.erb
<% if items.empty? %>
  <div class="mt-4 mb-6 not-found-box">
    <p>該当する商品は見つかりませんでした。</p>
    <p>カテゴリ、キーワードを変えてお試し下さい。</p>
    <% if scope_name == "amazon" %>
      <p><a href="https://www.amazon.co.jp/" target="_blank">Amazonで検索 <i class="fas fa-external-link-alt"></i></a></p>
    <% elsif scope_name == "rakuten" %>
      <p><a href="https://www.rakuten.co.jp/" target="_blank">楽天市場で検索 <i class="fas fa-external-link-alt"></i></a>&nbsp;&nbsp;<a href="https://books.rakuten.co.jp/" target="_blank">楽天ブックスで検索 <i class="fas fa-external-link-alt"></i></a></p>
    <% end %>
  </div>
<% else %>
  <% items.each do |item| %>
    <div class="mt-4 mb-6 box">
      <div class="row fix-height">
        <aside class="col-sm-4">
          <img class="rounded image-fix-width image-fix-height" src="<%= item[:image_url] %>" alt="">
        </aside>
        <div class="col-sm-8 parent">
          <p><a href="<%= item[:shop_url] %>" target="_blank" class="text-dark u-line multiline-text"><%= item[:name] %></a></p>
          <% if item[:sales_date] != "" %>
            <p>発売日 : <%= item[:sales_date] %></p>
          <% end %>
          <div class="col-sm-12 text-center children">
            <% if item[:price] == "" || item[:price] == nil %>
              <p><font size="6" color="red">価格情報が見当たりませんでした。</font></p>
            <% else %>
              <p><font size="6" color="red"><%= item[:price] %>（税込）</font></p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <p><a href="<%= item[:shop_url] %>" class="col-sm-12 btn btn-primary">ショップで確認</a></p>
        </div>
      </div>
    </div>
  <% end %>    
<% end %>

app/views/toppages/_search_result.html.erb
<% if items.empty? %>
  <div class="mt-4 mb-6 not-found-box">
    <p>該当する商品は見つかりませんでした。</p>
    <p>カテゴリ、キーワードを変えてお試し下さい。</p>
    <% if scope_name == "amazon" %>
      <p><a href="https://www.amazon.co.jp/" target="_blank">Amazonで検索 <i class="fas fa-external-link-alt"></i></a></p>
    <% elsif scope_name == "rakuten" %>
      <p><a href="https://www.rakuten.co.jp/" target="_blank">楽天市場で検索 <i class="fas fa-external-link-alt"></i></a>&nbsp;&nbsp;<a href="https://books.rakuten.co.jp/" target="_blank">楽天ブックスで検索 <i class="fas fa-external-link-alt"></i></a></p>
    <% end %>
  </div>
<% else %>
  <% items.each do |item| %>
    <div class="mt-4 mb-6 box">
      <div class="row fix-height">
        <aside class="col-sm-4">
          <img class="rounded image-fix-width image-fix-height" src="<%= item[:image_url] %>" alt="">
        </aside>
        <div class="col-sm-8 parent">
          <p><a href="<%= item[:shop_url] %>" target="_blank" class="text-dark u-line multiline-text"><%= item[:name] %></a></p>
          <% if item[:sales_date] != nil %>
            <p>発売日 : <%= item[:sales_date] %></p>
          <% end %>
          <% if item[:price] != nil %>
            <p><font color="red"><%= item[:price] %>（税込）</font></p>
          <% else %>
            <p><font color="red">価格情報が見当たりませんでした。</font></p>
          <% end %>
          <div class="col-sm-12 children">
            <% if item[:price] == nil || item[:jan_code] == nil %>
              <button type="button" class="col-sm-11 btn btn-primary" disabled="disabled">商品比較</button>
            <% else %>
              <%= form_with(url: comparison_path, scope: scope_name, method: :get, local: true) do |f| %>
                <%= f.hidden_field :name, :value => item[:name] %>
                <%= f.hidden_field :category, :value => category %>
                <%= f.submit '商品比較', class: "col-sm-11 btn btn-primary" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>    
<% end %>

app/views/toppages/comparison.html.erb
<h4 class="mt-4 pb-3 bg-warning text-white rounded-pill p-3">商品比較</h4>
<div class="row">
  <aside class="col-lg-6">
    <% if @is_rakuten_books %>
      <h4 class="mt-4 pb-2 border-bottom border-danger">楽天ブックス</h4>
    <% else %>
      <h4 class="mt-4 pb-2 border-bottom border-danger">楽天市場</h4>
    <% end %>
    <%= render 'toppages/item_display', {items: @rakuten_item, scope_name: "rakuten" } %>
  </aside>
  <div class="col-lg-6">
    <h4 class="mt-4 pb-2 border-bottom border-warning">Amazon</h4>
    <%= render 'toppages/item_display', {items: @amazon_item, scope_name: "amazon" } %>
  </div>
</div>

app/views/toppages/search.html.erb
<h4 class="mt-4 pb-3 bg-warning text-white rounded-pill p-3">検索結果（キーワード「<%= @keyword %>」カテゴリ「<%= @category_name %>」）</h4>
<div class="row">
  <aside class="col-lg-6">
    <% if @is_rakuten_books %>
      <h4 class="mt-4 pb-2 border-bottom border-danger">楽天ブックス</h4>
    <% else %>
      <h4 class="mt-4 pb-2 border-bottom border-danger">楽天市場</h4>
    <% end %>
    <%= render 'toppages/search_result', {items: @rakuten_item, scope_name: "rakuten", category: @category } %>
  </aside>
  <div class="col-lg-6">
    <h4 class="mt-4 pb-2 border-bottom border-warning">Amazon</h4>
    <%= render 'toppages/search_result', {items: @amazon_item, scope_name: "amazon", category: @category } %>
  </div>
</div>